#ifndef __E_SUBSYSTEM_COMMAND_HPP__
#define __E_SUBSYSTEM_COMMAND_HPP__

/// @brief The namespace for driftless library code
/// @author Matthew Backman
namespace driftless {

/// @brief The namespace for robot code
/// @author Matthew Backman
namespace robot {

/// @brief The namespace for subsystems code
/// @author Matthew Backman
namespace subsystems {

/// @brief The enum class for subsystem commands
/// @author Matthew Backman
enum class ESubsystemCommand {
  HOLONOMIC_DRIVE_TRAIN_SET_MOTION_VECTOR,
  HOLONOMIC_DRIVE_TRAIN_SET_NORMALIZED_MOTION_VECTOR,
  HOLONOMIC_DRIVE_TRAIN_SET_LINEAR_VELOCITY,
  HOLONOMIC_DRIVE_TRAIN_SET_ANGULAR_VELOCITY,
  HOLONOMIC_DRIVE_TRAIN_SET_NORMALIZED_LINEAR_VELOCITY,
  HOLONOMIC_DRIVE_TRAIN_SET_NORMALIZED_ANGULAR_VELOCITY,
  HOLONOMIC_DRIVE_TRAIN_SET_MODULE_VOLTAGE,
  HOLONOMIC_DRIVE_TRAIN_SET_CONTROL_TYPE,
  TANK_DRIVE_TRAIN_SET_VELOCITY,
  TANK_DRIVE_TRAIN_SET_VOLTAGE,
  ODOMETRY_SET_POSITION,
  ODOMETRY_SET_X,
  ODOMETRY_SET_Y,
  ODOMETRY_SET_THETA,
  ODOMETRY_RESET_X,
  ODOMETRY_RESET_Y,
  INTAKE_FRONT,
  INTAKE_BACK_IN,
  INTAKE_BACK_TO_HOOD,
  INTAKE_STOP_MOTION,
  INTAKE_DEPLOY_ARMS,
  INTAKE_RETRACT_ARMS,
  INTAKE_START_COLOR_SORT,
  INTAKE_PAUSE_COLOR_SORT,
  INTAKE_RESUME_COLOR_SORT,
  HOOD_SET_VOLTAGE,
  HOOD_OPEN_GATE,
  HOOD_CLOSE_GATE,
  HOOD_TOGGLE_GATE,
  HOOD_RAISE,
  HOOD_LOWER,
  HOOD_TOGGLE_RAISED,
  HOOD_EXTEND_DESCORE,
  HOOD_RETRACT_DESCORE,
  HOOD_EXTEND_DESCORE_HALF,
  HOOD_BUMP_UP,
  HOOD_BUMP_DOWN,
  HOOD_TOGGLE_BUMP,
  HOOD_SET_CURRENT_LIMIT,
  BRAKE_RETRACT,
  BRAKE_DEPLOY,
  RAKE_RETRACT,
  RAKE_DEPLOY

};
}  // namespace subsystems
}  // namespace robot
}  // namespace driftless
#endif